### ISSUE TITLE
[CV] right_side

### ISSUE THREAD

**Issue by schrodinger-cat** [alinasalnikova/path-of-the-Padawan#2]
```css
.right_side{
    left: 423px;
    right: -83px;
    margin-left: 65px;
    background: rgb(255,254,208);
    background: linear-gradient(197deg, rgba(255,254,208,1) 0%, rgba(255,255,255,1) 45%, rgba(232,251,255,1) 100%);
}
```

```css
.details-title{
    left: 453px;
    top: 133px;
    margin-bottom: 30px;
    padding-left: 40px;
}
```

```css
.header{
    left: 453px;
    top: 166px;
    margin-bottom: 10px;
}
```
и т.п

Значения `left`, `right` и `top` ничего не делают, поэтому лучше их удалить. Не стоит хранить не работающий код. 
И во всех остальных местах тоже стоит удалить (я не стал копипастить всё)

Опиши в комментарии, почему они работают сейчас, и что необходимо сделать что бы они начали работать
